modLoader = "javafml"
loaderVersion = "[43,)"
license = "LGPLv3"
issueTrackerURL = ""
[[mods]]
modId = "betterweather"
version = "1.0.0"
displayName = "Better Weather"
displayURL = ""
logoFile = "logo_text.png"
credits = ""
authors = "Corgi Taco, Mysticpasta1"
description = '''
A mod that adds more weather events! Some audio from: https://freesfx.co.uk/
'''
[[dependencies.betterweather]]
modId = "forge"
mandatory = true
versionRange = "[43.1.57,)"
ordering = "NONE"
side = "BOTH"
